server:
  servlet:
    context-path: /excemple
  port: 9088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
    ## jdbc连接mysql5 com.mysql.jdbc.Driver
    ## jdbc连接mysql6 com.mysql.cj.jdbc.Driver,需要指定时区 serverTimezone
    ## 在设定时区的时候，如果设定serverTimezone=UTC，会比中国时间早8个小时，如果在中国，可以选择Asia/Shanghai或者Asia/Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
